import React, { useState, useEffect } from 'react';
import {
  LineChart, Line, AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer
} from 'recharts';
import { leaderAPI } from '../services/api';

const LeaderDashboard = () => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [isHead, setIsHead] = useState(false);
  const [overviewData, setOverviewData] = useState(null);
  const [overviewLoading, setOverviewLoading] = useState(false);

  // Attendance & Members State
  const [members, setMembers] = useState([]);
  const [sectionInfo, setSectionInfo] = useState(null);
  const [attendance, setAttendance] = useState({});
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  // History State
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);

  // Manage Members State
  const [editingMember, setEditingMember] = useState(null);
  const [isMemberModalOpen, setIsMemberModalOpen] = useState(false);
  const [deletingMember, setDeletingMember] = useState(null);
  const [autogeneratedId, setAutogeneratedId] = useState('');

  // Reports/Graphs State
  const [trendsData, setTrendsData] = useState([]);
  const [trendsLoading, setTrendsLoading] = useState(false);
  const [trendsRange, setTrendsRange] = useState({ start: '', end: '' });

  useEffect(() => {
    loadMembers();
    loadHistory();
  }, []);

  useEffect(() => {
    checkSubmission();
  }, [selectedDate]);

  useEffect(() => {
    if (isHead) loadOverview();
  }, [selectedDate, isHead]);

  useEffect(() => {
    if (activeTab === 'reports') {
      loadTrends();
    }
  }, [activeTab]);

  const loadMembers = async () => {
    try {
      const response = await leaderAPI.getMembers();
      setSectionInfo({
        name: response.data.section_name,
        leader: response.data.leader_name
      });
      setMembers(response.data.members);
      setIsHead(Boolean(response.data.is_head));
      if (response.data.is_head && activeTab === 'dashboard') {
          // Default to overview for head leaders optionally
      }
      setAttendance({});
    } catch (error) {
      alert('Failed to load members');
    }
  };

  const loadHistory = async () => {
    try {
      const response = await leaderAPI.getHistory();
      setHistory(response.data);
    } catch (error) {
      console.error('Failed to load history:', error);
    } finally {
      setHistoryLoading(false);
    }
  };

  const loadOverview = async () => {
    setOverviewLoading(true);
    try {
      const response = await leaderAPI.getSectionOverview(selectedDate);
      setOverviewData(response.data);
    } catch (error) {
      console.error('Failed to load section overview:', error);
    } finally {
      setOverviewLoading(false);
    }
  };

  const loadTrends = async () => {
    setTrendsLoading(true);
    try {
      const response = await leaderAPI.getAttendanceTrends(90);
      setTrendsData(response.data.trends);
      setTrendsRange(response.data.date_range);
    } catch (error) {
      console.error('Failed to load attendance trends:', error);
    } finally {
      setTrendsLoading(false);
    }
  };

  const checkSubmission = async () => {
    try {
      const response = await leaderAPI.getAttendanceStatus(selectedDate);
      setSubmitted(response.data.submitted);
      if (response.data.attendance && response.data.attendance.length > 0) {
        const existing = {};
        response.data.attendance.forEach(a => {
          existing[a.member_id] = a.status;
        });
        setAttendance(existing);
      } else {
        setAttendance({});
      }
    } catch (error) {
      console.error('Failed to check submission:', error);
    }
  };

  const handleStatusChange = (memberId, status) => {
    if (submitted) return;
    setAttendance(prev => ({ ...prev, [memberId]: status }));
  };

  const handleSubmit = async () => {
    if (submitted) {
      alert('Attendance already submitted for this date');
      return;
    }

    if (Object.keys(attendance).length !== members.length) {
      alert(`Please mark attendance for all members before submitting. You have marked ${Object.keys(attendance).length} out of ${members.length}.`);
      return;
    }

    setLoading(true);
    try {
      const attendanceArray = Object.entries(attendance).map(([member_id, status]) => ({
        member_id: parseInt(member_id),
        status
      }));

      await leaderAPI.submitAttendance(selectedDate, attendanceArray);
      setSubmitted(true);
      
      // Refresh history silently and jump tabs
      loadHistory();
      setActiveTab('history');
      setMessage('Attendance submitted successfully!');
      setTimeout(() => setMessage(''), 5000);
    } catch (error) {
      alert(`Failed to submit: ${error.response?.data?.error || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  if (!sectionInfo) {
    return <div className="text-center py-8 font-medium text-gray-500">Loading Dashboard...</div>;
  }

  const presentMembers = members.filter(m => attendance[m.id] === 'present');
  const absentMembers = members.filter(m => attendance[m.id] === 'absent');
  const excusedMembers = members.filter(m => attendance[m.id] === 'excused');

  const handleMemberSave = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const memberData = {
      membership_id: formData.get('membership_id'),
      full_name: formData.get('full_name'),
      phone: formData.get('phone'),
      email: formData.get('email'),
      gender: formData.get('gender'),
      age_group: formData.get('age_group'),
    };

    setLoading(true);
    try {
      if (editingMember) {
        await leaderAPI.updateMember(editingMember.id, memberData);
        setMessage('Member updated successfully');
      } else {
        await leaderAPI.createMember(memberData);
        setMessage('Member added successfully');
      }
      setIsMemberModalOpen(false);
      setEditingMember(null);
      loadMembers(); // Refresh the list
      setTimeout(() => setMessage(''), 3000);
    } catch (error) {
      alert(`Error saving member: ${error.response?.data?.error || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleMemberDelete = async () => {
    if (!deletingMember) return;
    setLoading(true);
    try {
      await leaderAPI.deleteMember(deletingMember.id);
      setMessage('Member deleted successfully');
      setDeletingMember(null);
      loadMembers();
      setTimeout(() => setMessage(''), 3000);
    } catch (error) {
      alert(`Error deleting member: ${error.response?.data?.error || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-soft border border-gray-100 p-8">
        <h2 className="text-3xl font-bold tracking-tight text-gray-900 mb-2">Dashboard - {sectionInfo.name}</h2>
        <p className="text-gray-500 font-medium mb-6">Welcome, <span className="text-primary-600">{sectionInfo.leader}</span></p>

        {/* Tabs */}
        <div className="flex flex-wrap gap-3 mb-8 bg-gray-100/60 p-2.5 rounded-2xl shadow-inner border border-gray-200/60">
          {[
            { id: 'dashboard', label: 'Dashboard Overview', icon: '📊' },
            { id: 'members', label: 'Manage Members', icon: '👥' },
            { id: 'attendance', label: 'Take Attendance', icon: '📝' },
            { id: 'history', label: 'Submission History', icon: '🕒' },
            { id: 'reports', label: 'Graphs & Reports', icon: '📈' },
            ...(isHead ? [{ id: 'overview', label: 'Section Overview', icon: '👔' }] : [])
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id);
                setMessage(''); // clear message on tab change
              }}
              className={`flex items-center space-x-2 px-6 py-3 font-bold rounded-xl transition-all duration-300 transform ${
                activeTab === tab.id
                  ? 'bg-white text-primary-600 shadow-md scale-[1.03] border border-white'
                  : 'text-gray-500 hover:text-gray-800 hover:bg-white/50 hover:shadow-sm'
              }`}
            >
              <span className="text-xl">{tab.icon}</span>
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {message && (
          <div className="bg-emerald-50 border-l-4 border-emerald-500 text-emerald-800 px-4 py-3 rounded-r-lg mb-6 shadow-sm font-medium animate-fade-in">
            {message}
          </div>
        )}

        {/* Dashboard Tab */}
        {activeTab === 'dashboard' && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-4 animate-fade-in">
            <div className="relative overflow-hidden bg-gradient-to-br from-primary-600 to-indigo-800 p-8 rounded-3xl shadow-lg hover:shadow-2xl transition-all duration-400 transform hover:-translate-y-2 text-white group">
              <div className="absolute inset-0 pattern-bg opacity-10 group-hover:opacity-20 transition-opacity"></div>
              <div className="relative z-10">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-sm font-bold text-primary-200 uppercase tracking-widest">My Section Members</h3>
                  <div className="p-3 bg-white/10 rounded-2xl backdrop-blur-md">
                    <span className="text-3xl text-white block opacity-90 transition-transform group-hover:scale-110">👥</span>
                  </div>
                </div>
                <div className="flex items-baseline space-x-3 mt-8">
                  <p className="text-7xl font-black tracking-tighter drop-shadow-md">{members.length}</p>
                  <p className="text-primary-200 font-semibold tracking-wide">Total Assigned</p>
                </div>
              </div>
            </div>
            
            <div className="relative overflow-hidden bg-gradient-to-br from-emerald-500 to-teal-700 p-8 rounded-3xl shadow-lg hover:shadow-2xl transition-all duration-400 transform hover:-translate-y-2 text-white group">
              <div className="absolute inset-0 pattern-bg opacity-10 group-hover:opacity-20 transition-opacity"></div>
              <div className="relative z-10">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-sm font-bold text-emerald-100 uppercase tracking-widest">Total Submissions</h3>
                  <div className="p-3 bg-white/10 rounded-2xl backdrop-blur-md">
                    <span className="text-3xl text-white block opacity-90 transition-transform group-hover:scale-110">📝</span>
                  </div>
                </div>
                <div className="flex items-baseline space-x-3 mt-8">
                  <p className="text-7xl font-black tracking-tighter drop-shadow-md">{history.length}</p>
                  <p className="text-emerald-100 font-semibold tracking-wide">Recorded Sundays</p>
                </div>
              </div>
            </div>
            
            {submitted ? (
              <div className="md:col-span-2 mt-4 grid grid-cols-1 md:grid-cols-3 gap-6 animate-fade-in">
                {/* Present Column */}
                <div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
                  <h4 className="font-black text-emerald-800 flex justify-between items-center mb-4 border-b border-emerald-200 pb-3 uppercase tracking-wider text-sm">
                    <span>Present</span>
                    <span className="bg-emerald-500 text-white py-1 px-3 rounded-full text-xs font-bold shadow-sm">{presentMembers.length}</span>
                  </h4>
                  <ul className="space-y-3 max-h-48 overflow-y-auto custom-scrollbar pr-2">
                    {presentMembers.map(m => <li key={m.id} className="text-emerald-900 text-sm font-bold bg-white p-2 rounded-lg border border-emerald-100 shadow-sm">{m.full_name}</li>)}
                    {presentMembers.length === 0 && <li className="text-emerald-600/50 text-sm italic font-medium p-2 text-center">None</li>}
                  </ul>
                </div>
                {/* Absent Column */}
                <div className="bg-red-50 border border-red-100 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
                  <h4 className="font-black text-red-800 flex justify-between items-center mb-4 border-b border-red-200 pb-3 uppercase tracking-wider text-sm">
                    <span>Absent</span>
                    <span className="bg-red-500 text-white py-1 px-3 rounded-full text-xs font-bold shadow-sm">{absentMembers.length}</span>
                  </h4>
                  <ul className="space-y-3 max-h-48 overflow-y-auto custom-scrollbar pr-2">
                    {absentMembers.map(m => <li key={m.id} className="text-red-900 text-sm font-bold bg-white p-2 rounded-lg border border-red-100 shadow-sm">{m.full_name}</li>)}
                    {absentMembers.length === 0 && <li className="text-red-600/50 text-sm italic font-medium p-2 text-center">None</li>}
                  </ul>
                </div>
                {/* Excused Column */}
                <div className="bg-amber-50 border border-amber-100 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
                  <h4 className="font-black text-amber-800 flex justify-between items-center mb-4 border-b border-amber-200 pb-3 uppercase tracking-wider text-sm">
                    <span>Excused</span>
                    <span className="bg-amber-500 text-white py-1 px-3 rounded-full text-xs font-bold shadow-sm">{excusedMembers.length}</span>
                  </h4>
                  <ul className="space-y-3 max-h-48 overflow-y-auto custom-scrollbar pr-2">
                    {excusedMembers.map(m => <li key={m.id} className="text-amber-900 text-sm font-bold bg-white p-2 rounded-lg border border-amber-100 shadow-sm">{m.full_name}</li>)}
                    {excusedMembers.length === 0 && <li className="text-amber-600/50 text-sm italic font-medium p-2 text-center">None</li>}
                  </ul>
                </div>
              </div>
            ) : (
              <div className="md:col-span-2 mt-4 bg-gray-50 rounded-xl p-6 border border-gray-200 shadow-sm flex flex-col md:flex-row justify-between items-center">
                <div>
                  <h4 className="text-lg font-bold text-gray-800">Ready for Sunday?</h4>
                  <p className="text-gray-600 text-sm">Select the 'Take Attendance' tab to begin recording for {selectedDate}.</p>
                </div>
                <button 
                  onClick={() => setActiveTab('attendance')} 
                  className="mt-4 md:mt-0 bg-primary-600 hover:bg-primary-700 text-white font-bold py-3 px-6 rounded-lg shadow-soft transition-all transform hover:scale-105"
                >
                  Mark Attendance Now →
                </button>
              </div>
            )}
          </div>
        )}

        {/* Attendance Tab */}
        {activeTab === 'attendance' && (
          <div className="animate-fade-in">
            {/* Date Selector */}
            <div className="mb-8 p-6 bg-gray-50 rounded-xl border border-gray-100">
              <label className="block text-gray-700 font-bold mb-2">Select Sunday Date</label>
              <input
                type="date"
                value={selectedDate}
                onChange={(e) => setSelectedDate(e.target.value)}
                disabled={submitted}
                className="border border-gray-300 shadow-sm rounded-lg px-4 py-2 ring-1 ring-transparent focus:ring-primary-500 bg-white"
              />
              {submitted && (
                <div className="flex items-center space-x-2 text-emerald-600 mt-3 font-medium">
                  <span className="bg-emerald-100 px-2 py-0.5 rounded-full text-xs">✓</span>
                  <span>Submitted on {selectedDate}</span>
                </div>
              )}
            </div>

            {/* Attendance Cards */}
            <div className="mb-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {members.map(member => (
                <div key={member.id} className="glass-panel bg-white p-6 rounded-3xl hover:-translate-y-1 transition-all duration-300 relative overflow-hidden group">
                  <div className="absolute top-0 right-0 p-4 opacity-5 text-6xl group-hover:opacity-10 transition-opacity transform group-hover:scale-110 pointer-events-none">👤</div>
                  <div className="mb-6 relative z-10">
                    <p className="text-xs font-bold text-gray-400 mb-1 uppercase tracking-wider">ID: {member.membership_id}</p>
                    <h4 className="text-xl font-black text-gray-800 tracking-tight leading-tight">{member.full_name}</h4>
                    {member.phone && <p className="text-sm text-primary-600 font-bold mt-1">{member.phone}</p>}
                  </div>
                  <div className="flex flex-wrap gap-2 mt-auto relative z-10">
                    {['present', 'absent', 'excused'].map(status => (
                      <button
                        key={status}
                        onClick={() => handleStatusChange(member.id, status)}
                        disabled={submitted}
                        className={`flex-1 min-w-[30%] py-2.5 rounded-xl text-xs font-black uppercase tracking-wider transition-all duration-300 ${
                          attendance[member.id] === status
                            ? status === 'present'
                              ? 'bg-emerald-500 text-white shadow-glow ring-2 ring-emerald-500 ring-offset-2 transform scale-105'
                              : status === 'absent'
                              ? 'bg-red-500 text-white shadow-glow ring-2 ring-red-500 ring-offset-2 transform scale-105'
                              : 'bg-amber-500 text-white shadow-glow ring-2 ring-amber-500 ring-offset-2 transform scale-105'
                            : 'bg-gray-100 text-gray-500 hover:bg-gray-200 hover:text-gray-800 shadow-inner'
                        }`}
                      >
                        {status}
                      </button>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Submit Button */}
            <button
              onClick={handleSubmit}
              disabled={submitted || loading}
              className="w-full bg-gradient-to-r from-primary-600 to-secondary-600 hover:from-primary-500 hover:to-secondary-500 text-white font-black uppercase tracking-widest py-5 px-6 rounded-2xl transition-all duration-300 transform hover:-translate-y-1 hover:shadow-glow-lg disabled:opacity-50 disabled:hover:translate-y-0 disabled:hover:shadow-none text-xl flex justify-center items-center shadow-lg animate-pulse-glow"
            >
              {loading ? (
                 <span className="flex items-center"><svg className="animate-spin -ml-1 mr-4 h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>Submitting Records...</span>
              ) : submitted ? (
                 <span className="flex items-center space-x-2"><span>Checkmark Verified ✓</span></span>
              ) : (
                 <span className="flex items-center space-x-2"><span>Submit Attendance File</span> <span className="text-2xl ml-2">→</span></span>
              )}
            </button>
          </div>
        )}

        {/* History Tab */}
        {activeTab === 'history' && (
          <div className="animate-fade-in">
            {historyLoading ? (
              <div className="text-center py-8 text-gray-500">Loading history...</div>
            ) : history.length === 0 ? (
              <div className="text-center py-12 bg-gray-50 rounded-xl border border-gray-100">
                <span className="text-4xl mb-4 block">📋</span>
                <p className="text-gray-500 font-medium text-lg">No attendance records submitted yet.</p>
              </div>
            ) : (
              <div className="overflow-x-auto rounded-xl border border-gray-200 shadow-sm">
                <table className="min-w-full divide-y divide-gray-100">
                  <thead className="bg-gray-50/80 backdrop-blur-sm">
                    <tr>
                      <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Date</th>
                      {isHead && <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Leader</th>}
                      <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Time Submitted</th>
                      <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Records</th>
                      <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Status</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-100">
                    {history.map((record, index) => (
                      <tr key={index} className="hover:bg-primary-50/40 transition-colors duration-150">
                        <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900">
                          {new Date(record.date).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        </td>
                        {isHead && (
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-blue-700">
                            {record.leader_name}
                          </td>
                        )}
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {new Date(record.submitted_at).toLocaleString()}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-bold">
                          {record.records_count}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="px-3 py-1 inline-flex text-xs leading-5 font-bold rounded-full bg-emerald-100 text-emerald-800 border border-emerald-200 shadow-sm">
                            Recorded ✓
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* Reports & Graphs Tab */}
        {activeTab === 'reports' && (
          <div className="animate-fade-in space-y-8">
            <div className="bg-gradient-to-r from-blue-50 to-purple-50 p-6 rounded-xl border border-blue-100 shadow-sm">
              <h3 className="text-xl font-bold text-gray-900 mb-2">Attendance Reports & Visualization</h3>
              <p className="text-gray-600 font-medium">Visual analysis of your section's attendance patterns over the last 90 days</p>
            </div>

            {trendsLoading ? (
              <div className="text-center py-12 flex justify-center items-center">
                <svg className="animate-spin -ml-1 mr-3 h-8 w-8 text-primary-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                <span className="text-gray-500 font-bold text-lg">Loading Reports...</span>
              </div>
            ) : trendsData.length === 0 ? (
              <div className="text-center py-12 bg-gray-50 rounded-xl border border-gray-100">
                <span className="text-4xl mb-4 block">📊</span>
                <p className="text-gray-500 font-medium text-lg">No attendance data available for graphing yet.</p>
                <p className="text-gray-400 text-sm mt-2">Start submitting attendance to see reports and trends.</p>
              </div>
            ) : (
              <>
                {/* Summary Stats Row */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  {(() => {
                    const total = trendsData.reduce((sum, d) => sum + d.total_members, 0);
                    const present = trendsData.reduce((sum, d) => sum + d.present_count, 0);
                    const absent = trendsData.reduce((sum, d) => sum + d.absent_count, 0);
                    const avgAttendance = trendsData.length > 0 ? Math.round((present / total) * 100) : 0;
                    return (
                      <>
                        <div className="bg-blue-50 border border-blue-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                          <div className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-1">Total Sessions</div>
                          <div className="text-3xl font-extrabold text-blue-600">📅 {trendsData.length}</div>
                        </div>
                        <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                          <div className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-1">Avg Attendance Rate</div>
                          <div className="text-3xl font-extrabold text-emerald-600">✅ {avgAttendance}%</div>
                        </div>
                        <div className="bg-green-50 border border-green-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                          <div className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-1">Total Present</div>
                          <div className="text-3xl font-extrabold text-green-600">👥 {present}</div>
                        </div>
                        <div className="bg-red-50 border border-red-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                          <div className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-1">Total Absent</div>
                          <div className="text-3xl font-extrabold text-red-600">❌ {absent}</div>
                        </div>
                      </>
                    );
                  })()}
                </div>

                {/* Charts Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                  {/* Attendance Trend Line Chart */}
                  <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                    <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                      <span className="mr-2">📈</span> Attendance Trend Over Time
                    </h4>
                    <ResponsiveContainer width="100%" height={300}>
                      <LineChart data={trendsData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis
                          dataKey="date"
                          tick={{ fontSize: 12 }}
                          tickFormatter={(val) => new Date(val).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                        />
                        <YAxis tick={{ fontSize: 12 }} />
                        <Tooltip
                          contentStyle={{ borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                          labelFormatter={(val) => new Date(val).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        />
                        <Legend />
                        <Line type="monotone" dataKey="present_count" stroke="#10b981" strokeWidth={2} name="Present" dot={{ r: 3 }} activeDot={{ r: 5 }} />
                        <Line type="monotone" dataKey="absent_count" stroke="#ef4444" strokeWidth={2} name="Absent" dot={{ r: 3 }} activeDot={{ r: 5 }} />
                        <Line type="monotone" dataKey="excused_count" stroke="#f59e0b" strokeWidth={2} name="Excused" dot={{ r: 3 }} activeDot={{ r: 5 }} />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>

                  {/* Stacked Area Chart */}
                  <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                    <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                      <span className="mr-2">📊</span> Attendance Composition
                    </h4>
                    <ResponsiveContainer width="100%" height={300}>
                      <AreaChart data={trendsData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis
                          dataKey="date"
                          tick={{ fontSize: 12 }}
                          tickFormatter={(val) => new Date(val).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                        />
                        <YAxis tick={{ fontSize: 12 }} />
                        <Tooltip
                          contentStyle={{ borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                          labelFormatter={(val) => new Date(val).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        />
                        <Legend />
                        <Area type="monotone" dataKey="present_count" stackId="1" stroke="#10b981" fill="#10b981" name="Present" />
                        <Area type="monotone" dataKey="absent_count" stackId="1" stroke="#ef4444" fill="#ef4444" name="Absent" />
                        <Area type="monotone" dataKey="excused_count" stackId="1" stroke="#f59e0b" fill="#f59e0b" name="Excused" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>

                  {/* Current Status Distribution Pie Chart */}
                  <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                    <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                      <span className="mr-2">🥧</span> Latest Attendance Distribution
                    </h4>
                    <ResponsiveContainer width="100%" height={300}>
                      <PieChart>
                        <Pie
                          data={[
                            { name: 'Present', value: trendsData[trendsData.length - 1]?.present_count || 0, color: '#10b981' },
                            { name: 'Absent', value: trendsData[trendsData.length - 1]?.absent_count || 0, color: '#ef4444' },
                            { name: 'Excused', value: trendsData[trendsData.length - 1]?.excused_count || 0, color: '#f59e0b' }
                          ]}
                          cx="50%"
                          cy="50%"
                          labelLine={false}
                          label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
                          outerRadius={80}
                          fill="#8884d8"
                          dataKey="value"
                        >
                          {[
                            { name: 'Present', value: 0, color: '#10b981' },
                            { name: 'Absent', value: 0, color: '#ef4444' },
                            { name: 'Excused', value: 0, color: '#f59e0b' }
                          ].map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={entry.color} />
                          ))}
                        </Pie>
                        <Tooltip />
                        <Legend />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>

                  {/* Attendance Rate Bar Chart */}
                  <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                    <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                      <span className="mr-2">📉</span> Weekly Attendance Rate
                    </h4>
                    <ResponsiveContainer width="100%" height={300}>
                      <BarChart data={trendsData.map(d => ({
                        ...d,
                        attendance_rate: d.total_members > 0 ? Math.round((d.present_count / d.total_members) * 100) : 0
                      }))}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis
                          dataKey="date"
                          tick={{ fontSize: 12 }}
                          tickFormatter={(val) => new Date(val).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                        />
                        <YAxis tick={{ fontSize: 12 }} domain={[0, 100]} tickFormatter={(val) => `${val}%`} />
                        <Tooltip
                          contentStyle={{ borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                          labelFormatter={(val) => new Date(val).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                          formatter={(value) => [`${value}%`, 'Attendance Rate']}
                        />
                        <Bar dataKey="attendance_rate" fill="#6366f1" radius={[4, 4, 0, 0]} name="Attendance Rate" />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                {/* Data Table */}
                <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <span className="mr-2">📋</span> Detailed Data
                  </h4>
                  <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="px-6 py-3 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Date</th>
                          <th className="px-6 py-3 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Present</th>
                          <th className="px-6 py-3 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Absent</th>
                          <th className="px-6 py-3 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Excused</th>
                          <th className="px-6 py-3 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Total</th>
                          <th className="px-6 py-3 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Attendance Rate</th>
                        </tr>
                      </thead>
                      <tbody className="bg-white divide-y divide-gray-100">
                        {trendsData.slice().reverse().map((day, idx) => {
                          const rate = day.total_members > 0 ? Math.round((day.present_count / day.total_members) * 100) : 0;
                          return (
                            <tr key={idx} className="hover:bg-gray-50">
                              <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900">
                                {new Date(day.date).toLocaleDateString(undefined, { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' })}
                              </td>
                              <td className="px-6 py-4 whitespace-nowrap text-center font-bold text-emerald-600">{day.present_count}</td>
                              <td className="px-6 py-4 whitespace-nowrap text-center font-bold text-red-600">{day.absent_count}</td>
                              <td className="px-6 py-4 whitespace-nowrap text-center font-bold text-amber-600">{day.excused_count}</td>
                              <td className="px-6 py-4 whitespace-nowrap text-center font-bold text-gray-900">{day.total_members}</td>
                              <td className="px-6 py-4 whitespace-nowrap text-center">
                                <span className={`px-3 py-1 inline-flex text-xs font-bold rounded-full ${rate >= 80 ? 'bg-emerald-100 text-emerald-800' : rate >= 60 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800'}`}>
                                  {rate}%
                                </span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              </>
            )}
          </div>
        )}

        {/* Section Overview Tab for Head Leaders */}
        {activeTab === 'overview' && isHead && (
          <div className="animate-fade-in">
             <div className="mb-6 bg-blue-50/50 p-6 rounded-xl border border-blue-100 flex flex-col sm:flex-row items-start sm:items-center justify-between shadow-sm">
                <div>
                   <h3 className="font-bold text-blue-900 text-lg">Section Overview for {selectedDate}</h3>
                   <p className="text-sm text-blue-700 font-medium mt-1">Monitoring subleader attendance submissions for '{sectionInfo.name}'</p>
                </div>
                <div className="mt-4 sm:mt-0">
                  <input
                    type="date"
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                    className="border border-blue-200 shadow-sm rounded-lg px-4 py-2 ring-1 ring-transparent focus:ring-blue-500 bg-white text-blue-900 font-semibold"
                  />
                </div>
             </div>

             {overviewLoading ? (
                <div className="text-center py-12 flex justify-center items-center">
                   <svg className="animate-spin -ml-1 mr-3 h-8 w-8 text-primary-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                   <span className="text-gray-500 font-bold text-lg">Loading Subleader Tracking</span>
                </div>
             ) : overviewData ? (
                <div className="space-y-6">
                   <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                      <div className="bg-white border border-gray-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                         <div className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Leaders Submitted</div>
                         <div className="text-3xl font-extrabold text-primary-600">{overviewData.stats.total_submitted_leaders} <span className="text-lg text-gray-400">/ {overviewData.stats.total_leaders}</span></div>
                      </div>
                      <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                         <div className="text-xs font-bold text-emerald-800 uppercase tracking-widest mb-1">Total Present</div>
                         <div className="text-3xl font-extrabold text-emerald-600">{overviewData.stats.present}</div>
                      </div>
                      <div className="bg-red-50 border border-red-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                         <div className="text-xs font-bold text-red-800 uppercase tracking-widest mb-1">Total Absent</div>
                         <div className="text-3xl font-extrabold text-red-600">{overviewData.stats.absent}</div>
                      </div>
                      <div className="bg-amber-50 border border-amber-100 rounded-xl p-5 shadow-sm text-center transform transition-transform hover:scale-105">
                         <div className="text-xs font-bold text-amber-800 uppercase tracking-widest mb-1">Total Excused</div>
                         <div className="text-3xl font-extrabold text-amber-600">{overviewData.stats.excused}</div>
                      </div>
                   </div>

                   <div className="overflow-x-auto rounded-xl border border-gray-200 shadow-sm mt-8">
                      <table className="min-w-full divide-y divide-gray-200">
                         <thead className="bg-gray-50/80 backdrop-blur-sm">
                           <tr>
                              <th className="px-6 py-4 text-left text-xs font-bold text-gray-600 uppercase tracking-wider">Subleader Name</th>
                              <th className="px-6 py-4 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Submission Status</th>
                              <th className="px-6 py-4 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Present</th>
                              <th className="px-6 py-4 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Absent</th>
                              <th className="px-6 py-4 text-center text-xs font-bold text-gray-600 uppercase tracking-wider">Excused</th>
                           </tr>
                         </thead>
                         <tbody className="bg-white divide-y divide-gray-100">
                           {overviewData.subleaders.map(sl => (
                              <tr key={sl.leader_id} className="hover:bg-primary-50/30 transition-colors">
                                 <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900 border-r border-gray-50">{sl.leader_name}</td>
                                 <td className="px-6 py-4 whitespace-nowrap text-center border-r border-gray-50">
                                    {sl.submitted ? 
                                       <span className="bg-emerald-100 text-emerald-800 text-xs font-extrabold px-4 py-1.5 rounded-full border border-emerald-200 shadow-sm">VERIFIED ✓</span> : 
                                       <span className="bg-gray-100 text-gray-600 text-xs font-extrabold px-4 py-1.5 rounded-full border border-gray-200">PENDING</span>
                                    }
                                 </td>
                                 <td className="px-6 py-4 whitespace-nowrap text-center font-extrabold text-emerald-600 bg-emerald-50/20">{sl.stats.present}</td>
                                 <td className="px-6 py-4 whitespace-nowrap text-center font-extrabold text-red-600 bg-red-50/20">{sl.stats.absent}</td>
                                 <td className="px-6 py-4 whitespace-nowrap text-center font-extrabold text-amber-600 bg-amber-50/20">{sl.stats.excused}</td>
                              </tr>
                           ))}
                           {overviewData.subleaders.length === 0 && (
                              <tr>
                                <td colSpan={5} className="px-6 py-12 text-center text-gray-500 font-medium">No leaders found in this section.</td>
                              </tr>
                           )}
                         </tbody>
                      </table>
                   </div>
                </div>
             ) : (
                <div className="text-center py-8 text-gray-500 font-medium">Failed to load data.</div>
             )}
          </div>
        )}

      </div>
      
      {/* Manage Members Tab */}
      {activeTab === 'members' && (
        <div className="bg-white rounded-xl shadow-soft border border-gray-100 p-8 animate-fade-in mt-6">
          <div className="flex justify-between items-center mb-6">
             <h3 className="text-2xl font-bold text-gray-900">My Section Members</h3>
             <button
               onClick={() => { 
                 setEditingMember(null); 
                 // Generate a mix of letters and numbers for the ID
                 const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
                 let newId = 'MEM-';
                 for (let i = 0; i < 8; i++) newId += chars.charAt(Math.floor(Math.random() * chars.length));
                 setAutogeneratedId(newId);
                 setIsMemberModalOpen(true); 
               }}
               className="bg-primary-600 hover:bg-primary-700 text-white px-5 py-2 rounded-xl font-bold transition shadow-soft flex items-center space-x-2"
             >
               <span className="text-xl">+</span>
               <span>Add Member</span>
             </button>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-gray-200 shadow-sm">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50/80 backdrop-blur-sm">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">ID</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Name</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Phone</th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-100">
                {members.map((member) => (
                  <tr key={member.id} className="hover:bg-primary-50/40 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{member.membership_id}</td>
                    <td className="px-6 py-4 whitespace-nowrap font-bold text-gray-900">{member.full_name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{member.phone || '-'}</td>
                    <td className="px-6 py-4 whitespace-nowrap space-x-4">
                      <button
                        onClick={() => { setEditingMember(member); setIsMemberModalOpen(true); }}
                        className="text-primary-600 hover:text-primary-800 text-sm font-bold transition-colors"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => setDeletingMember(member)}
                        className="text-red-500 hover:text-red-700 text-sm font-bold transition-colors"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
                {members.length === 0 && (
                  <tr>
                    <td colSpan="4" className="px-6 py-12 text-center text-gray-500 font-medium italic">You have no members assigned to this section yet. Add your first member above.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Render Modals Globally Contextual */}
      {isMemberModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in">
          <div className="bg-white rounded-3xl shadow-2xl max-w-lg w-full p-8 border border-gray-100">
            <div className="flex justify-between items-center mb-6 border-b border-gray-100 pb-4">
              <h2 className="text-2xl font-black text-gray-900">{editingMember ? 'Edit Member' : 'Add Member'}</h2>
              <button 
                onClick={() => setIsMemberModalOpen(false)} 
                className="text-gray-400 hover:text-gray-800 text-3xl transition-colors outline-none focus:outline-none"
              >&times;</button>
            </div>
            
            <form onSubmit={handleMemberSave} className="space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Membership ID <span className="text-red-500">*</span></label>
                  <input required name="membership_id" defaultValue={editingMember ? editingMember.membership_id : autogeneratedId} disabled={!!editingMember}
                    className="w-full border border-gray-300 rounded-xl px-4 py-2 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all" />
                  {editingMember && <span className="text-xs text-gray-400 block mt-1">Cannot edit ID</span>}
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Full Name <span className="text-red-500">*</span></label>
                  <input required name="full_name" defaultValue={editingMember?.full_name}
                    className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Phone</label>
                  <input name="phone" defaultValue={editingMember?.phone}
                    className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all" />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Email</label>
                  <input type="email" name="email" defaultValue={editingMember?.email}
                    className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Gender</label>
                  <select name="gender" defaultValue={editingMember?.gender || ''} className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary-500 outline-none">
                    <option value="">Select...</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Age Group</label>
                  <select name="age_group" defaultValue={editingMember?.age_group || ''} className="w-full border border-gray-300 rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary-500 outline-none">
                    <option value="">Select...</option>
                    <option value="Children">Children</option>
                    <option value="Youth">Youth</option>
                    <option value="Adult">Adult</option>
                    <option value="Senior">Senior</option>
                  </select>
                </div>
              </div>
              
              <div className="flex justify-end space-x-3 pt-6 border-t border-gray-100 mt-6">
                <button type="button" onClick={() => setIsMemberModalOpen(false)}
                  className="px-6 py-2.5 rounded-xl font-bold bg-gray-100 text-gray-600 hover:bg-gray-200 transition-colors">
                  Cancel
                </button>
                <button type="submit" disabled={loading}
                  className="px-6 py-2.5 rounded-xl font-bold bg-primary-600 text-white hover:bg-primary-700 shadow-glow transition-all">
                  {loading ? 'Saving...' : 'Save Member'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {deletingMember && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in">
           <div className="bg-white rounded-3xl shadow-2xl max-w-sm w-full p-8 border border-gray-100 text-center">
              <span className="text-5xl mb-4 block animate-bounce">🗑️</span>
              <h3 className="text-2xl font-black text-gray-900 mb-2">Delete Member?</h3>
              <p className="text-gray-500 font-medium mb-6">Are you sure you want to delete <strong>{deletingMember.full_name}</strong>? This action cannot be undone.</p>
              
              <div className="flex justify-center space-x-3">
                <button type="button" onClick={() => setDeletingMember(null)}
                  className="px-6 py-2 rounded-xl font-bold bg-gray-100 text-gray-600 hover:bg-gray-200 transition-colors">
                  Cancel
                </button>
                <button type="button" onClick={handleMemberDelete} disabled={loading}
                  className="px-6 py-2 rounded-xl font-bold bg-red-600 text-white hover:bg-red-700 shadow-glow transition-all">
                  {loading ? 'Deleting...' : 'Delete'}
                </button>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};

export default LeaderDashboard;
